### ISSUE TITLE
Import useful changes from https://github.com/avuton/controldlna

### ISSUE THREAD

**Issue by aabaker** [aabaker/controldlna#3]
Likely candidates are
https://github.com/avuton/controldlna/commit/fff867d2b658061a08447b88a506ecd09971920d
https://github.com/avuton/controldlna/commit/2e675bd6f2cacc4ff5a35fc314911c883b82917c

Also consider
https://github.com/avuton/controldlna/commit/c598d0ca1694055c8246b20f9a2b076c4bf00f03
are these streams currently being closed at all?

**Comment by Velociraptor85** [comment]
maybe close this since avuton deletet his fork

**Comment by aabaker** [comment]
Ohh whatsnames, I thought some of those hinted at real possible but obscure bugs but the fact avuton had reformatted the code made them non trivial to pull across. Lesson leared, pull such things into a branch while they are still around in future.
